---
title: "[Java] 예외 떠넘기기"
description: ""
date: "2022-09-10T22:30:45+09:00"
thumbnail: ""
categories:
  - "Java"
tags:
  - "Java"


---
<!--more-->

- 경우에 따라서는 메소드를 호출한 곳으로 예외를 떠넘길 수 있다.
    - 이때 사용하는 키워드가 `throws`
- `throws` 키워드
    - 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할
    - `throws`키워드 뒤에 떠넘길 예외 클래스를 쉼표로 구분해서 나열
    
    ```java
    리턴타입 메소드명(매개변수, ...) throws 예외클래스1, 예외클래스2, ... {
    }
    ```
    
    - 발생할 수 있는 예외의 종류별로 `throws` 뒤에 나열하는 것이 일반적
    - `throws Exception`만으로 모든 예외를 간단히 떠넘길 수 있다.
    
    ```java
    리턴타입 메소드명(매개변수, ...) throws Exception {
    }
    ```
    
- `throws` 키워드가 붙어있는 메소드는 반드시 `try` 블록 내에서 호출되어야 한다.
    - `catch` 블록에서 떠넘겨 받은 예외를 처리
    - `thorws` 키워드가 있는 `method2()`를 `method1()`에서 호출하는 방법
    
    ![Untitled](/images/lang_java/exception/예외_떠넘기기/Untitled.png)
    
- `method1()`에서도 `try`-`catch` 블록으로 예외를 처리하지 않고 `throws` 키워드로 다시 예외를 넘길 수 있다.
    - `method1()`을 호출하는 곳에서 `try`-`catch` 블록을 사용해 예외를 처리해야 한다.
    
    ```java
    public void method1() throws ClassNotFoundException {
    	method2();
    }
    ```
    
- 자바 API 도큐먼트를 보면 클래스 생성자와 메소드 선언부에 `throws` 키워드가 붙어있는 것을 흔히 볼 수 있다.
    - ex) Class의 `forName()` API 도큐먼트
        
        ![Untitled](/images/lang_java/exception/예외_떠넘기기/Untitled%201.png)
        
    - 이러한 생성자와 메소드를 사용하고 싶은 경우, 반드시 `try`-`catch` 블록으로 예외 처리를 해야한다.
        - 아니면 `throws`를 다시 사용하여 예외를 호출한 곳으로 떠넘겨야 한다.
        - 그렇지 않을 경우 컴파일 오류 발생
- ex) `forName()`
    - `forName()` 메소드 선언부 뒤에 `throws ClassNotFoundException`이 붙어 있기 때문에 `forName()` 메소드를 호출할 때  `try`-`catch` 블록으로 예외처리를 하거나, `throws`로 예외를 떠넘겨야 한다.
    - `Class.forName()` 메소드를 사용하는 `findClass()` 메소드는 예외를 떠넘기고, `findClass()`를 호출하는 `main()` 메소드에서 `try`-`catch` 블록을 사용해서 예외 처리를 함
    
    ```java
    public class ThrowsEx {
    
    	public static void main(String[] args) {
    		try {
    			findClass();
    		}catch(ClassNotFoundException e) {
    			System.out.println("클래스가 존재하지 않음");
    		}
    
    	}
    	
    	public static void findClass() throws ClassNotFoundException{
    		Class clazz = Class.forName("java.lang.String2");
    	}
    
    }
    ```
    
    ![Untitled](/images/lang_java/exception/예외_떠넘기기/Untitled%202.png)
    
- `main()` 메소드에서도 `throws` 키워드를 사용해서 예외를 떠넘기는 것이 가능
    - 결국 JVM이 최종적으로 예외 처리를 하게 된다.
    - JVM은 예외의 내용을 콘솔(Console)에 출력하는 것으로 예외 처리를 한다.
    
    ```java
    public static void main(String[] args throws ClassNotFoundException {
    	findClass();
    }
    ```
    
- `main()` 메소드에서 `throws Exception`을 붙이는 것은 좋지 못한 예외 처리 방법
    - 프로그램 사용자는 프로그램이 알 수 없는 예외 내용을 출력하고 종료되는 것을 좋아하지 않는다.
    - `main()`에서 `try`-`catch` 블록으로 예외를 최종 처리하는 것이 바람직

---

## References

- 이것이 자바다 신용권의 Java 프로그래밍 정복 - 신용권 지음, 한빛미디어 출판